name: Docker Image CI

on:
  push:
    branches:
     - main

permissions:
  contents: read

jobs:
  docker-release:
    name: Docker release to Google Artifact Registry
    runs-on: ubuntu-22.04

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - id: checkout
        name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - id: auth
        name: Authenticate with Google Cloud
        uses: step-security/google-github-auth@f0e5c257a9534a30b5df12f43329c1eb7b85a5be # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: projects/259610024247/locations/global/workloadIdentityPools/github-actions/providers/github-actions-access
          service_account: github-actions@discord-access-prd.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: us-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          tags: |
            us-east1-docker.pkg.dev/discord-access-prd/access/access:latest
          build-args: |
            SENTRY_RELEASE=${{ github.sha }}
            PUSH_SENTRY_RELEASE=true
          secrets: |
            "SENTRY_ORG=${{ secrets.SENTRY_ORG }}"
            "SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}"
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
